[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[phases.build]
cmds = []

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
